########################################################
#                ROBO DC.PAWPAM v.1.3                  #
########################################################
services:
  phpapp:
    build:
      context: ./phpapp
      target: builder
    image: phpapp:1.3
    container_name: phpapp
    env_file: ./.env
    environment:
      MYSQL_HOST: mdb
    networks:
      - phpappnet
    ports:
      - "8080:80"
    depends_on: [mdb]
    volumes:
      - ./phpapp/src:${APP_MAIN_DIR}
      - ./storage:${APP_STORAGE_DIR}
      - ./logs:${APP_LOG_DIR}
      # - ./logs/phpapp:${APP_MAIN_DIR}/logs
    cap_add:
      - SYS_TIME
      - SYS_NICE

  mdb:
    build: ./database
    image: phpappdb:1.3
    container_name: mdb
    networks:
      - phpappnet
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
    command: --character-set-server=${DB_CHARSET} --collation-server=${DB_CHARSET}_general_ci --default-authentication-plugin=mysql_native_password
    restart: always
    expose:
      - "${DB_PORT}"
    ports:
      - "${DB_PORT}:${DB_PORT}"

  # cache:
  #     image: redis:5-alpine
  #     container_name: cache
  #     volumes:
  #         - cachedata:/data
  #     networks:
  #         - phpappnet
  #     entrypoint: redis-server --appendonly yes
  #     restart: always

  # PhpMyAdmin container - remove in production!
  # Uncomment when needed
  phpma:
    image: phpmyadmin/phpmyadmin
    container_name: phpma
    restart: unless-stopped
    links:
      - mdb
    networks:
      - phpappnet
    ports:
      - "8888:80"
    environment:
      PMA_HOST: mdb
      PMA_PORT: ${DB_PORT}
      PMA_USER: root
      PMA_PASSWORD: ${DB_ROOT_PASSWORD}
      PMA_PORTS: 3306,3307
      MAX_EXECUTION_TIME: 3000000
      UPLOAD_LIMIT: 6G
      PMA_QUERYHISTORYDB: 1
      PMA_QUERYHISTORYMAX: 1000
    depends_on:
      - mdb

networks:
  phpappnet:
    driver: bridge

volumes:
  dbdata:
    driver: local
  phpapp:
    driver: local
  # cachedata:
  #     driver: local
